version: '3.7'
services:
  db1:
    image: mariadb:focal
    restart: always
    container_name: db1
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=dujiaoka
      - MYSQL_USER=dujiaoka
      - MYSQL_PASSWORD=dujiaoka
    volumes:
      - ./mysql/db1:/var/lib/mysql

  db2:
    image: mariadb:focal
    restart: always
    container_name: db2
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=epusdt
      - MYSQL_USER=epusdt
      - MYSQL_PASSWORD=epusdt
    volumes:
      - ./mysql/db2:/var/lib/mysql

  nginx:
    image: nginx:latest
    restart: always
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/config/:/etc/nginx/:ro

  dujiaoka:
    image: jiangjuhong/dujiaoka
    restart: always
    container_name: dujiaoka
    ports:
      - 8080:80
      - 9090:9000
    environment:
      - WEB_DOCUMENT_ROOT=/app/public

  redis:
    image: redis:latest
    restart: always
    container_name: redis
    volumes:
      - ./redis/data:/data

  epusdt:
    image: sengnie/epusdt:latest
    restart: always
    container_name: epusdt
    volumes:
      - ./epusdt/epusdt.conf:/app/.env
    ports:
      - 8000:8000